name: chatbot
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  device_calendar: ^0.1.1
  add_2_calendar: ^1.4.0

  url_launcher: ^3.0.0
  google_maps_flutter: ^0.5.27+3
  flutter_dialogflow: ^0.1.0
  flutter:
    sdk: flutter
  
 
  firebase_auth: ^0.16.1
  cupertino_icons: ^0.1.3
  flutter_dialogflow: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - images/logo_login.jpg
    - images/logo.png
    - assets/credentials.json


